name: terraform-config
description: https://github.com/champ-oss/action-terraform-config

inputs:
  branch:
    description: 'Used to select state file and .tfvars files'
    default: ${{ github.ref_name }}

runs:
  using: "composite"
  steps:
    - run: pip install -r ${GITHUB_ACTION_PATH}/requirements.txt
      shell: bash
    - run: python ${GITHUB_ACTION_PATH}/main.py
      shell: bash
      env:
        BRANCH: ${{ inputs.branch }}
