name: terraform-config
description: https://github.com/champ-oss/action-terraform-config

inputs:
  branch:
    default: ${{ github.ref_name }}

env:
  BRANCH: ${{ inputs.branch }}

runs:
  using: "composite"
  steps:
    - run: pip install -r ${GITHUB_ACTION_PATH}/requirements.txt
      shell: bash
    - run: python ${GITHUB_ACTION_PATH}/main.py
      shell: bash
